# Site settings
title: Mingway_Hu的Blog
email: humingwei@live.cn
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "http://humingwei.com" # the subpath of your site, e.g. /blog/
url: "http://humingwei.com" # the base hostname & protocol for your site
#twitter_username: Mingway
github_username:  humingwei

# Build settings
markdown: kramdown
